name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to the Streamlit app
        run: |
          curl -sI https://credit-risk-predictor-dashboard.streamlit.app/ | head -n 1
